apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-pagetest-ingress
spec:
  rules:
    - host: app.pagetest.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
