apiVersion: v1
kind: Secret
metadata:
  name: app-pagetest-secrets
  namespace: production
type: Opaque
data:
  APP_KEY: <base64-encoded-app-key>
  DB_DATABASE: <base64-encoded-db-name>
  DB_USERNAME: <base64-encoded-username>
  DB_PASSWORD: <base64-encoded-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: app-pagetest-secrets
  namespace: stage
type: Opaque
data:
  APP_KEY: <base64-encoded-app-key>
  DB_DATABASE: <base64-encoded-db-name>
  DB_USERNAME: <base64-encoded-username>
  DB_PASSWORD: <base64-encoded-password>
