apiVersion: batch/v1
kind: Job
metadata:
  name: app-pagetest-migrate
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: gcr.io/your-gcp-project/app-pagetest:latest
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - secretRef:
                name: app-pagetest-secrets
