apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pagetest-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-pagetest-worker
  template:
    metadata:
      labels:
        app: app-pagetest-worker
    spec:
      containers:
        - name: worker
          image: gcr.io/your-gcp-project/app-pagetest:latest
          command: ["php", "artisan", "queue:work"]
          envFrom:
            - secretRef:
                name: app-pagetest-secrets
